on:
  push:
    branches:
      - master

jobs:

  prepare:
    name: Build docker and push it
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build container image latest ver
        run: docker build --pull -t index.docker.io/abielfiletus/epb:cms-v0.0.1 .

      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Push Image to Docker
        run: docker push abielfiletus/epb:cms-v0.0.1

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 8288
          script: |
            cd development/epb
            docker compose -f docker-compose-cms.yml pull
            docker compose -f docker-compose-cms.yml down
            docker compose -f docker-compose-cms.yml --project-name epb-cms up -d
